### ISSUE TITLE
CM0 KeySchedule for Decryption

### ISSUE THREAD

**Issue by matbok** [jnk0le/cortexm-AES#6]
Hi,
do you plan to add the KeySchedule for the decryption also for the CM0 target?
Thanks!

**Comment by jnk0le** [comment]
all current CM0 decryptions use forward expanded key.

the *_keyschedyule_dec functions perform equivalent inverse transform required in Tbox implementions only.

**Comment by matbok** [comment]
you're right, Thanks. I close the issue.
