### ISSUE TITLE
CM3 unrolled implementations are broken due to syntax

### ISSUE THREAD

**Issue by covsh** [jnk0le/cortexm-AES#9]
Hello
I'm experimenting with the STM32L151 Cortex M3 (STM32CubeIDE, GNU Tools for STM32 (9-2020-q2-update))
I have decoder  
`aes::mode::CBC<256, aes::target::CM3_1T_deconly, aes::mode::target::CBC_GENERIC> tcbc;`
and decoding result is always wrong.
Also try CM3_1T, CM3_1T_unrolled, CM3_1T_unrolled_deconly and so on and have no luck.
(unrolled versions prodece **Hard Falult** on CM3_1T_unrolled_dec_round)

As soon as I switch to
`aes::mode::CBC<256, aes::target::CM0_FASTMULsBOX, aes::mode::target::CBC_GENERIC> tcbc;`
or 
`aes::mode::CBC<256, aes::target::CM0_sBOX, aes::mode::target::CBC_GENERIC> tcbc;`
The decoding is going great.

What am I doing wrong?

**Comment by jnk0le** [comment]
I'll check later. For now, keep in mind that CBC still doesn't have proper padding implemented  (#2), other possibility is that something is unaligned (#5).
If you could provide at which instruction it hardfaults it would help a bit,

**Comment by covsh** [comment]
> Hello I'm experimenting with the STM32L151 Cortex M3 (STM32CubeIDE, GNU Tools for STM32 (9-2020-q2-update)) I have decoder `aes::mode::CBC<256, aes::target::CM3_1T_deconly, aes::mode::target::CBC_GENERIC> tcbc;` and decoding result is always wrong.

It's my mistake.  I set only **setEncKey** and decoding work well (surprised) on CM0 implementation. But then I switched to CM3, result is always wrong. **setDecKey** solved the problem. Decoding was successful!

>If you could provide at which instruction it hardfaults it would help a bit,

Hard Falult is still present on CM3_1T_unrolled implementation.

![image](https://github.com/jnk0le/cortexm-AES/assets/13795008/a0a6347c-8223-4233-a18b-1dc53b565c15)
![image](https://github.com/jnk0le/cortexm-AES/assets/13795008/1db5bddb-33e3-4d44-bad4-85dbd16f5bd3)
![image](https://github.com/jnk0le/cortexm-AES/assets/13795008/e3e38578-a651-41a3-adb2-5a19ee4bb9b2)

**Comment by jnk0le** [comment]
> It's my mistake. I set only setEncKey and decoding work well (surprised) on CM0 implementation. But then I switched to CM3, result is always wrong. setDecKey solved the problem. Decoding was successful!

only Tbox implementations need equivalent inverse tranform of the key for decryption. I recommend to always set decrypton key. (expands to nothing on sBOX implementations)

>Hard Falult is still present on CM3_1T_unrolled implementation.

Ah, it's because asm includes use different syntax than gas normally and the `#` are comments instead of preprocessor.
